namespace: "fortinet"
name: "fortiwebcloud"
version: "1.0.3"
description: "A collection of Ansible Modules for FortiwebCloud"
readme: "README.md"
authors:
    - Xilong Li (@xilongli14)
    - Xiangrang Zhang (@xrzhang3707)
    - Chengwei Hu (@godwindy)
dependencies: { }
license:
    - "MIT"
tags:
    - fortiwebcloud
    - networking
    - WAF
    - security
    - fortinet
repository: "https://github.com/fortinet/fortiwebcloud-ansible"
homepage: "https://www.fortinet.com"
issues: "https://github.com/fortinet/fortiwebcloud-ansible/issues"
