---

- name: Execute cloud api
  hosts: fortiwebcloud01
  gather_facts: no
  collections:
    - fortinet.fortiwebcloud
  connection: httpapi
  vars:
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
    ansible_httpapi_port: 443
    application_name:  "YOUR_APP_NAME"

  tasks:
    - name: Delete the application.
      cloudwaf_app_delete:
        api_token: "{{fortiwebcloud_api_token}}"  #if you prefer access token based authentication, add this line.
        app_name: "{{application_name}}"
